### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Reeto29** [Reeto29/Basketball_Bot_Discord#1]
- [x] Add Player Images

**Comment by Reeto29** [comment]
- [ ] Bulletproof user input for '=player' command, for example, if the user only enters the first name, use the first name search, provide name options
- [ ] Include additional stats for the players such as height

**Comment by Daggerpov** [comment]
Making '=customplayer (customplayer name)' command to look up custom players:

- [x] if statement for it
- [ ] when making new player, give option to draw them in a little popout paint tool (could be an application that starts running that I can make, or somehow integrate with discord itself)
- [ ] stats will be stored in a basic database with same categories as regular players from the nba

Making '=playcustom (customplayer name)' command to accumulate stats as a custom player
- [ ] accumulate stats by reacting to a message, will have to remove reaction after every one
- [ ] down the line, we could make scenarios for custom players to react to like pasting images that would correspond to which stat the user should add to.

**Comment by Reeto29** [comment]
More player statistics
- [ ] Scroll through pages for different player statistics using reactions

Low priority enhancements:
- [ ] Maybe a 'typing' indicator, so that users can understand that the bot is processing the command
- [ ] Command to clear past messages
